//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GVIEntities : DbContext
    {
        public GVIEntities()
            : base("name=GVIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        [DbFunction("GVIEntities", "fn_API_GetData")]
        public virtual IQueryable<fn_API_GetData_Result> fn_API_GetData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_API_GetData_Result>("[GVIEntities].[fn_API_GetData]()");
        }
    
        [DbFunction("GVIEntities", "fn_API_Get_DataSource")]
        public virtual IQueryable<fn_API_Get_DataSource_Result> fn_API_Get_DataSource()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_API_Get_DataSource_Result>("[GVIEntities].[fn_API_Get_DataSource]()");
        }
    
        [DbFunction("GVIEntities", "fn_API_Get_DataRecoleccion")]
        public virtual IQueryable<fn_API_Get_DataRecoleccion_Result> fn_API_Get_DataRecoleccion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_API_Get_DataRecoleccion_Result>("[GVIEntities].[fn_API_Get_DataRecoleccion]()");
        }
    }
}
