//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Re_Data_Reference
    {
        public int id { get; set; }
        public int DocEntry { get; set; }
        public string Factura { get; set; }
        public string DesAlmDes { get; set; }
        public string U_CardName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Valida_Picking { get; set; }
        public Nullable<int> Rotulo { get; set; }
        public string Paqueteria { get; set; }
        public Nullable<int> Prioridad { get; set; }
        public Nullable<int> version_data { get; set; }
        public Nullable<System.DateTime> fecha_version { get; set; }
    }
}
